name: Backup jca_spots.csv
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wget
        run: wget -O "`date +%Y%m%d_%H%M%S`.csv" https://monumen.to/jca_spots.csv
        working-directory: jca
      - name: Commit downloaded file
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.json > /dev/null 2>&1
          git commit -m "Deploy" > /dev/null 2>&1
          git push origin main
