name: Get ISS current location
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: wget
        run: wget -O "`date +%Y%m%d_%H%M%S`.json"  http://api.open-notify.org/iss-now.json