name: Get ISS current location
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl http://api.open-notify.org/iss-now.json